### ISSUE TITLE
Add support for ENV variables

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms-google-recaptcha#11]
They are not working as expected when used for the siteKey and secretKey values

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1bq9v)

**Comment by jrrdnx** [comment]
I've noticed this happening recently as well. I know it used to work, but I'm unable to pinpoint at which version it stopped working (I'm guessing somewhere around the refactoring/invisible recaptcha support commits). It saves the environment variable fine, but doesn't get parsed when being output.

**Comment by BenParizek** [comment]
This has been fixed in v1.2.0
