### ISSUE TITLE
Invisible reCAPTCHA v2 throws js error

### ISSUE THREAD

**Issue by VdVChiel** [barrelstrength/craft-sprout-forms-google-recaptcha#12]
### Description (screenshots, logs, ...)
When using the invisible google reCAPTCHA v2, you get a js error 'Cannot read property `AppendChild` of null' for variable 'c'

![Schermafbeelding 2020-02-13 om 12 19 02](https://user-images.githubusercontent.com/10195598/74429519-6d3e2080-4e5b-11ea-8a91-9b5f3eaa7825.png)

### Steps to reproduce

1. Create an API key for Google reCAPTCHA v2
2. In the settings for Sprout Forms, select reCAPTCHA v2 - invisible
3. Set site key & secret key
4. Go to a form on your site
5. Inspect with Chrome inspector and select 'Console' tab
6. Error should show

### Additional info

- Craft version: 3.4.4.1
- PHP version: 7.3
- Database driver & version:  MariaDB 10.3.16
- Plugins & versions: Sprout forms reCAPTCHA 1.1.0 & Sprout Forms 3.8.0.2

**Comment by BenParizek** [comment]
@ChielRobarov Do you happen to be using custom templates? The reCAPTCHA code does make a few assumptions about the DOM within the form tag. I am working on getting this better documented. If that might be your situation, I can explain further.

**Comment by VdVChiel** [comment]
> @ChielRobarov Do you happen to be using custom templates? The reCAPTCHA code does make a few assumptions about the DOM within the form tag. I am working on getting this better documented. If that might be your situation, I can explain further.

Yes we are using custom forms templates with sprout forms.

**Comment by riusi88** [comment]
@ChielRobarov , I'm wondering if you might have run into the same problem as my recent issue:
https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/13#issue-570168223

Are you by chance doing anything that might override the default id attribute on the form tag? You may be doing this one of two ways. 1. via [Rendering options ](https://sprout.barrelstrengthdesign.com/docs/forms/rendering-options.html), or 2. via custom form templates that might remove [this line of code](https://github.com/barrelstrength/craft-sprout-forms/blob/2bc4d3bb5df3abe2d1065e63b4ef4260dad03be5/src/templates/_components/formtemplates/accessible/form.twig#L19). I also believe if you don't have this[ line of code](https://github.com/barrelstrength/craft-sprout-forms/blob/2bc4d3bb5df3abe2d1065e63b4ef4260dad03be5/src/templates/_components/formtemplates/accessible/form.twig#L43) within your custom templates, the captcha may not work.

**Comment by VdVChiel** [comment]
@riusi88 @BenParizek We found the solution, you need to make sure your submit button is inside a div with the "submit" class.

Strange that it worked before for us, don't know if it's an update from google itself or from the reCAPTCHA plugin that broke the code.

Thanks for the help!

**Comment by BenParizek** [comment]
@ChielRobarov That should solve it for now. I'm re-opening this as I do want to update our core JS logic so that you're less dependent on what we think the HTML structure and class names in your template should be.

**Comment by BenParizek** [comment]
@VdVChiel @riusi88 This has improved in v1.2.0 and we now target that submit button directly based instead of relying on the submit wrapper. Thanks for your feedback.
