### ISSUE TITLE
Recaptcha Javascript error | TypeError: form is null

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/craft-sprout-forms-google-recaptcha#13]
After some troubleshooting, I'm fairly certain I understand the problem and the solution. I hope you find this helpful @BenParizek to building a quick fix. 

### Steps to reproduce

1. Have Sprout Forms installed, as well as Sprouts Google reCAPTCHA plugin. 
2. Enable Google reCAPTCHA spam protection.
3. Create a form
4. Use Sprouts Rendering Options to override the forms id attribute within your frontend template

### Deeper Explanation
In your templates, if you implement some Sprout Form rendering options that include an override for the form ID, for example:

> {% set options = {
>     "id": "my-form"
> } %}
> 
> {{ craft.sproutForms.displayForm("formHandle", options) }}

You will receive a JS error warning you that the form object does not exist `TypeError: e is null`. This I believe is being caused by [this line of code](https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/blob/09d71efd9de101a59af45befc7cde8bff2c6c01d/src/web/assets/recaptcha/src/js/recaptcha_v2_invisible.js#L22) which is looking for the Forms ID in order to create the Form object. The "formId" generated by this plugin isn't taking into consideration the possibility that a user might override the forms id attribute via Sprouts Template Rendering Options. Therefore, the reCAPTCHA plugin is unable to find the form within the DOM due to the mismatched id's.

If you remove the "id" override from your Rendering options, the reCAPTCHA displays properly. 

### Proposed solution 
Since it looks like the plugins JS is already looking at data attributes within the DOM, I recommend adding a new data attribute to Sprouts front end form tag that injects the forms database id. This way the JS can be certain that the id's will always match what's in the db. This solutions would require commits to both this repository and the Sprout Forms repo as well. 
Perhaps there's another solution I'm not thinking about that won't require people to update their custom form templates with the new attribute, but it's just a thought. Hope this helps!

### Additional info

- Craft version: 3.4.8
- Sprout Pro: 3.8.3
- Google reCAPTCHA for Sprout Forms version: 1.1.0

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1houb)

**Comment by BenParizek** [comment]
Thanks @riusi88 

We're looking into a solution like you've proposed, or some way to let the user have more control over what they want their ID to be that also works with the default JS. I believe our code may also assume that you have a <div> with the class `.submit` around your submit button – another thing we'll try to make less dependent on the default code when we have a chance.

For now, the best workaround is to use those default ID and class names or to override the `form.twig` file and swap out our default Javascript for your own where you update those assumptions.

**Comment by BenParizek** [comment]
@riusi88 This has been addressed in v1.2.0 and you should be able to use whatever ID you wish on the form now. Thanks for reporting.
