### ISSUE TITLE
SproutFormsGoogleRecaptchaCheckbox is not defined

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms-google-recaptcha#14]
### Description (screenshots, logs, ...)
We're using Sentry for bug tracking, and its picking up a huge amount of errors:

```
ReferenceError: SproutFormsGoogleRecaptchaCheckbox is not defined
  at sproutFormsRecaptchaOnloadCallback (/page-name:2198:5)
  at GO (/recaptcha/releases/qpy2aGtSgsYPZzCoYWjcaBCo/recaptcha__en.js:510:339)
  at None (/recaptcha/releases/qpy2aGtSgsYPZzCoYWjcaBCo/recaptcha__en.js:520:57)
  at KD (/recaptcha/releases/qpy2aGtSgsYPZzCoYWjcaBCo/recaptcha__en.js:301:122)
  at wM (/recaptcha/releases/qpy2aGtSgsYPZzCoYWjcaBCo/recaptcha__en.js:520:36)
...
(2 additional frame(s) were not displayed)
```

Loading the page manually many times, doesn't throw the error, so it seems to be pretty sporadic. But, looking at the source code of the page, I'd say its a script loading order issue.

Note the order of scripts being loaded:
```
<script src="/cpresources/29081b2d/recaptcha_v2_checkbox.js?v=1584504470" async="" defer=""></script>
<script src="https://www.google.com/recaptcha/api.js?onload=sproutFormsRecaptchaOnloadCallback&amp;render=explicit&amp;hl=en" async="" defer=""></script>
<script>if (typeof sproutFormsRecaptchaOnloadCallback === 'undefined') {
    var sproutFormsRecaptchaOnloadCallback = function() {
    new SproutFormsGoogleRecaptchaCheckbox({
    siteKey: 'xxxxxxxxx',
    theme: 'light',
    size: 'normal',
    customValidityText: "Please fill out this field.",
    grecaptcha: grecaptcha
    });
    };
    };
</script>
```

I would say the inline script content needs to be added first, before the onload callback for the recaptcha code. In some cases, it looks like the Google API script is being loaded faster than the inline script (I suppose possibly cached).

Using the latest versions of everything.

**Comment by BenParizek** [comment]
Thanks @engram-design. I'm currently reworking the javascript around the submit logic. There are a few scenarios that we can improve right now. I'll consider this as I sort things out and update here once I do.

**Comment by BenParizek** [comment]
@engram-design The latest release 1.2.0 attempts to address this issue. Let me know if you still see any errors.
