### ISSUE TITLE
Expected parameter 1 to be an array, null given in

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms-google-recaptcha#17]
Error displays in control panel on Captcha page

**Comment by olets** [comment]
Looks like this is probably the same as what I just ran into, though the exact error message is different, so I won't open a new ticket. With this only a couple hours old I wouldn't be surprised if you're already on it. For good measure, I've opened a PR with my fix #18. Feel free to close the PR

**Comment by BenParizek** [comment]
This has been resolved in the latest release.
