### ISSUE TITLE
reCaptcha language settings for Multisite

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-forms-google-recaptcha#19]
The recaptcha settings seems to have only global language settings. The result is „I'am not a robot“ message only in one language.

Is it possible choose recaptcha language based on current site setting? (en for en, de for de, fr for fr…)

**Comment by BenParizek** [comment]
@lexislav We initially looked into this and it wasn't obvious how we could do it. The Craft and reCAPTCHA supported language options are different so some assumptions would need to be made. 

I'll treat this as a feature request as it'd be nice to have but can't promise a timeline as it will likely take some experimenting.

**Comment by lexislav** [comment]
Well I did a small change to v2_checkbox.twig:

{% set locale = craft.i18n.getCurrentLocale()|slice(0,2) %}


{# reCAPTCHA logic. Must come after `onloadCallback` js above. #}
{%- do view.registerJsFile('https://www.google.com/recaptcha/api.js?onload=sproutFormsRecaptchaOnloadCallback&render=explicit&hl=' ~ locale ?? settings.language, {
    async: true,
    defer: true
}) -%}

And it does what it should. At least for my needs (german, english, czech, slovak, french…)

**Comment by BenParizek** [comment]
@lexislav Nice solution. I've taken it as inspiration and added a similar feature in the latest release v1.4.0

The "Language" setting has been renamed to "Language Fallback" and the reCAPTCHA plugin will now try to dynamically match a language to the current Craft locale. If it doesn't find a match, it will look for a more generic match (say, if `en-AU` is selected in Craft and not found in Google reCAPTCHA's available options, we'll try to match the shorter `en`), and if that is not found, the plugin will use the Captcha Language setting.
