### ISSUE TITLE
Validation does not work with badge+disabled css

### ISSUE THREAD

**Issue by olets** [barrelstrength/craft-sprout-forms-google-recaptcha#20]
### Description (screenshots, logs, ...)

In Chome, with the badge variant, if I toggle on "disable css" and submit the form without doing the captcha, the `g-recaptcha-response` validation message does not appear. There is an error in the browser inspector console

```
An invalid form control with name="g-recaptcha-response" is not focusable.
```

### Steps to reproduce

1. Choose the badge option
2. Turn on disable CSS
3. Submit the reCAPTCHA-protected form without completing the captcha

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2.24
- Database driver & version:  MySQL 5.7.29
- Plugins & versions:
  ![image](https://user-images.githubusercontent.com/3282350/81419058-a4029a80-911b-11ea-9dbd-c8032a5ea807.png)

**Comment by BenParizek** [comment]
Thanks @olets. We'll look into this and let you know when we have a solution.

**Comment by BenParizek** [comment]
@olets What's the goal you are trying to achieve by disabling the CSS?

The CSS being disabled is specifically the CSS that makes the HTML5 invalid hint appear. So, this is expected behavior. Are there any other issues that you are seeing because the CSS is enabled?

**Comment by olets** [comment]
Got it, thanks. No specific need to have css disabled. Would naming the option something like "disable validation" be clearer? For me "disable css" carries no implication of a change that could affect validation or result in a console error.

**Comment by BenParizek** [comment]
@olets The implementation of this feature with CSS feels a bit hacky to begin with but it seems to be the most common way people are using to support the HTML5 validation behavior.

 I'll update the instruction text in the next release to indicate that the CSS is used for the validation.
