### ISSUE TITLE
Google Checkbox Recpatcha throws a "Uncaught in Promise" error after checked

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms-google-recaptcha#22]
https://share.barrelstrength.co/NQuDzqWJ

**Comment by TomDeSmet** [comment]
This issue is closed but I still get the error. Link in the only reply doesn't work so... should this be fixed?

**Comment by BenParizek** [comment]
@TomDeSmet This was from a while ago. Can you provide version info and steps to recreate the error you are seeing?

**Comment by TomDeSmet** [comment]
Craft CMS: 3.6.10
Sprout forms: 3.13.2.3
Google reCAPTCHA for Sprout Forms: 1.4.0 

```
Uncaught (in promise) Timeout (f)
Uncaught (in promise) Timeout
Uncaught (in promise) Timeout (f)
Uncaught (in promise) Timeout (j)
```

**Comment by tpssyndicate** [comment]
I'm getting the exact same error messages. When trying to check the reCAPTCHA, it spins for quite a while and then throws the timeout error messages...

Craft CMS: 3.7.62
Sprout forms: 3.13.11
Google reCAPTCHA for Sprout Forms: 1.4.0

Anything we can try?

**Comment by BenParizek** [comment]
Sprout Forms v3.13.12 fixes a bug where async form submissions were not properly wrapped in the promise chain which could have caused issues like this while processing Google ReCaptcha.

While I haven't been able to reproduce to confirm this is the same issue, as this is an older ticket, I'm closing it out. If this continues for anybody, please re-open with additional detail.
