### ISSUE TITLE
reCAPTCHA fails to render same reCAPTCHA-id on the same page

### ISSUE THREAD

**Issue by espensgr** [barrelstrength/craft-sprout-forms-google-recaptcha#27]
We have the contact form two places on the same page, and when reCAPTCHA tries to render it get's this:
![image](https://user-images.githubusercontent.com/3862891/89889150-7a9d5300-dbd1-11ea-94ea-9e194ad82652.png)
And this is because in the `recaptcha_v2_invisible.js` you use the `recaptchaContainer.id` instead of just the dom element. ref container in the documentation [here](https://developers.google.com/recaptcha/docs/invisible#js_api)

[edit]: i get this on the checkbox version also.

So in my case it tries to add the same id two times, and it fails.
Could you test this to see if this is the case?

**Comment by BenParizek** [comment]
Thanks for the details @espensgr. It does look like we should just be using the container there. I'll take a closer look and update this thread when I have more.

**Comment by BenParizek** [comment]
And it looks like you have PR waiting for me already!

**Comment by espensgr** [comment]
Yeah, thought that would be easier 😄

**Comment by BenParizek** [comment]
This is added in v1.4.1
