### ISSUE TITLE
Add support for additional reCAPTCHA options

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms-google-recaptcha#3]
We currently only support reCAPTCHA v2 "I'm not a robot" checkbox.

Consider adding support for additional captcha integrations for

- v2 "Invisible reCAPTCHA badge"
- v3

They will all be part of one plugin but may be handled with different Captcha Integrations that can be selected in the settings.

**Comment by ghost** [comment]
Is this still something that is planned?

**Comment by BenParizek** [comment]
I'll be reviewing the ReCaptcha implementation this week @mustasj. I will update this thread with what I determine.

**Comment by BenParizek** [comment]
@mustasj I've just released v1.1.0 which adds support for several additional options:

- Added support for Invisible reCAPTCHA v2
- Added Invisible reCAPTCHA settings for Language, Theme, and Badge Type including an 'Inline Text' option to display a line of text terms instead of a badge
- Added Checkbox reCAPTCHA settings for Language, Theme, and Size
- Added support for using reCAPTCHA when displaying multiple forms on a page

**Comment by ghost** [comment]
Nice, thanks!
