### ISSUE TITLE
JS error, everything going to spam

### ISSUE THREAD

**Issue by artmem** [barrelstrength/craft-sprout-forms-google-recaptcha#31]
I'm trying to use an invisible reCAPTCHA badge, but I'm getting a js error on page load:

 Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.addEventListener')

When I have reCAPTCHA enabled, every submission goes to spam with the error ["Google reCAPTCHA can't be blank."]

If I disable it, the form works fine.

I'm not using a custom form template (well, I customized some of the html elements, but I didn't touch any of the actual twig elements).

Full error message is attached.
![error](https://user-images.githubusercontent.com/1660827/99557860-bf7f1580-2988-11eb-87bf-c2b43dbddef6.jpg)

**Comment by BenParizek** [comment]
Thanks for reporting @artmem 

I'll look into this soon and update this thread when I have more.

**Comment by BenParizek** [comment]
Also update thread here once released:
https://craftcms.stackexchange.com/questions/36729/sprout-forms-recaptcha-js-error-everything-flagged-as-spam

**Comment by alexrubin** [comment]
@BenParizek has there been any traction on this issue?

**Comment by BenParizek** [comment]
@alexrubin Not yet.

I apologize for the lack of support recently. I've been focused on an underlying architecture/migration issue affecting many of our plugins that has lead to several ongoing migration problems. Once I get through that (hopefully this month) I'll be circling back to all or other bugs.

I understand that's not ideal and am doing my best to prioritize the items that get me back into a position for more consistent support all around moving forward.

For now, if this is a blocker it may be best to work around this by trying another captcha, service-based spam filter (like Cloudflare), or plugin and I will update this thread as soon as I can get back to the general bugs.

**Comment by BenParizek** [comment]
Sprout Forms v3.13.12 fixes a bug where async form submissions were not properly wrapped in the promise chain which could have caused issues like this while processing Google ReCaptcha.

As this is an older bug, I'm closing it out. If anybody runs into this again, please create a new bug or re-open with new comments.
