### ISSUE TITLE
Support for Google Recaptcha v3

### ISSUE THREAD

**Issue by VdVChiel** [barrelstrength/craft-sprout-forms-google-recaptcha#34]
### The problem (description, use case, screenshots...)
Not being able to add v3 Recaptchas through the plugin.

### The solution (that feature you'd like to see)
Add recaptcha v3 support

### Alternatives you've considered
Not using the plugin and adding our own custom code to the forms.

**Comment by BenParizek** [comment]
@VdVChiel to my understanding, reCAPTCHA v3 requires a more custom implementation and is not a good fit for us to add default support:

> reCAPTCHA v3 returns a score for each request without user friction. The score is based on interactions with your site and enables you to take an appropriate action for your site

- https://developers.google.com/recaptcha/docs/v3

If you need to develop a custom scoring system based on how a user is interacting with your site, the best way to do this will be to create a custom Captcha implementation. You could potentially copy one of our default Captcha integrations as a starting point: 

- https://sprout.barrelstrengthdesign.com/docs/forms/custom-captchas.html
