### ISSUE TITLE
Migrations fail if allowAdminChanges is set to false

### ISSUE THREAD

**Issue by michaelramuta** [barrelstrength/craft-sprout-forms-google-recaptcha#46]
I was getting this error when trying to run the migrations "Not Supported: Changes to the project config are not possible while in read-only mode."

Here is a PR to fix this! https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/pull/45

**Comment by BenParizek** [comment]
Thanks, Michael.

**Comment by BenParizek** [comment]
This is added in v1.4.1
