### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by romainpoirier** [barrelstrength/craft-sprout-forms-google-recaptcha#57]
### The problem (description, use case, screenshots...)
On the [Sprout Documentation ](https://sprout.barrelstrengthdesign.com/docs/craft-v4/forms/custom-captchas.html#captcha-class)there's this link: [Google Recaptcha for Sprout Forms](https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha).

Where in the [READ ME ](https://github.com/barrelstrength/sprout-forms-google-recaptcha/blob/v1/README.md) of the _sprout-forms-google-recaptcha_ plugin, there's nothing more.

### The solution (that feature you'd like to see)
Make the documetation accessible.

**Comment by BenParizek** [comment]
I'm working on simplifying the docs as we get upgraded to Craft v4 and ReCaptcha will be integrated and no longer be a separate plugin. 

The documentation linked to is for developers who are adding custom captcha integrations. Captchas are extensible in Sprout Forms so once you install the a Captcha Integration (like the Google ReCaptcha plugin does), the ability to enable/disable it and any settings appear on the Sprout Forms Spam Protection settings page.

For installed captchas, the more appropriate doc page is this one:
https://sprout.barrelstrengthdesign.com/docs/craft-v3/forms/spam-protection.html
