### ISSUE TITLE
Settings page broken

### ISSUE THREAD

**Issue by away86** [barrelstrength/craft-sprout-forms-google-recaptcha#8]
### Description (screenshots, logs, ...)
CP settings page for Sprout Forms Google reCaptcha plugin is broken. It shows a blank page. No JS error, no error logged in web.log, no error logged in phperrors.log.

Also a side question: can I ask you which table in db stores the Google reCaptcha key & secret please? In case this issue can't be fixed soon, at least I can go in and update them in db directly.

Thanks.

### Steps to reproduce

As above

### Additional info

- Craft version: 3.2.10
- PHP version: 7.1.29
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: Sprout Forms: 3.4.0, Sprout Forms Google Recaptcha: 1.0.5

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@away86 This is on our list to clean up. The Settings page should not appear at all and has no settings to display. 

Once the Sprout Forms ReCAPTCHA plugin is installed, the settings for the ReCAPTCHA plugin should be visible in: **Sprout Forms -> Settings -> Spam Protection**

The data is currently stored in Craft's `info` table in the giant json blob in the `config` column.

I'll close this item out but a ticket for the same issue is open here if you have any more details you want to add: https://github.com/barrelstrength/craft-sprout-forms/issues/332
